version: '2'

services:
  redis:
    image: 'redis:3.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'

  website:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        "app:app"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/semantive'
    ports:
      - '8000:8000'

  celery:
    build: .
    command: celery worker -l info -A celery_run
    volumes:
      - '.:/semantive'

volumes:
  redis: